server:
  port: 8090
  servlet:
    context-path: /gateway

spring:
  application:
    name: gateway-service
  profiles:
    active: dev

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
